[package]
name = "neuralchain"
version = "0.1.0"
edition = "2021"
authors = ["Équipe NeuralChain"]
description = "Une blockchain innovante avec un système PoW neuronal adaptatif"
readme = "README.md"
repository = "https://github.com/neuralchain/neuralchain"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "cryptocurrency", "neural-network", "consensus", "defi"]
categories = ["cryptography", "finance", "network-programming"]

[dependencies]
# Dépendances fondamentales
anyhow = "1.0"
bincode = "1.3"
ed25519-dalek = "2.0"
hex = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.25", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# Cryptographie et sérialisation
sha2 = "0.10"
ed25519-dalek = "2.0"
k256 = { version = "0.13", features = ["ecdsa"] }
rand = "0.8"
hex = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Stockage et base de données
rocksdb = "0.21"
lmdb-rs = "0.7"

# Réseau P2P 
libp2p = { version = "0.52", features = ["tokio", "noise", "yamux", "gossipsub", "kad", "identify"] }
warp = "0.3"
uuid = { version = "1.3", features = ["v4", "serde"] }

# Utilitaires
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
num_cpus = "1.15"
parking_lot = "0.12"

# Machine learning (pour le PoW neuronal)
ndarray = "0.15"
smartcore = "0.3"

[dev-dependencies]
tokio-test = "0.4"
proptest = "1.1"
mockall = "0.11"
test-log = "0.2"
tempfile = "3.5"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
